### ISSUE TITLE
Error at inptools 

### ISSUE THREAD

**Issue by hra1981** [sdteffen/inptools#16]
Hi Steffen
after running inptools for convert inp to shap file I got this error:
"fatal error :epanet returned error 224 when opening .
Thanks

**Comment by sdteffen** [comment]
inp2shp expects a valid INP file. Please add tanks or reservoirs to your network in order to use inp2shp (These could be dummy ones that you remove after the conversion)

Input Error 224: no tanks or reservoirs in network.

A list of all EPANET error codes:
http://epanet.de/documentation/errorcodes.html
